services:
  - type: web
    name: projet5-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./run_streamlit.sh"
    envVars:
      - key: MLFLOW_TRACKING_URI
        value: http://ec2-52-209-5-80.eu-west-1.compute.amazonaws.com:5000